/* libpcre++/config.h.  Generated by configure.  */
/* libpcre++/config.h.in.  Generated automatically from configure.in by autoheader 2.13.  */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have the <dlfcn.h> header file.  */
#define HAVE_DLFCN_H 1

/* Define if you have the <sstream> header file.  */
#define HAVE_SSTREAM 1

/* Define if you have the <stdexcept> header file.  */
#define HAVE_STDEXCEPT 1

/* Define if you have the <string> header file.  */
#define HAVE_STRING 1

/* Define if you have the <vector> header file.  */
#define HAVE_VECTOR 1

/* Define if you have the pcre library (-lpcre).  */
#define HAVE_LIBPCRE 1

/* Name of package */
#define PACKAGE "libpcre++"

/* Version number of package */
#define VERSION "0.9.5"

